# AUTHENTICATION / AUTHORIZATION BACKENDS
auth_backends.1 = internal
auth_backends.2 = cache

# HTTP AUTH BACKEND CONFIG
auth_http.http_method = post

auth_http.user_path     = http://host.docker.internal:8080/api/messaging/auth/user
auth_http.vhost_path    = http://host.docker.internal:8080/api/messaging/auth/vhost
auth_http.resource_path = http://host.docker.internal:8080/api/messaging/auth/resource
auth_http.topic_path    = http://host.docker.internal:8080/api/messaging/auth/topic

# HTTP AUTH CACHE
auth_cache.cached_backend = http
auth_cache.cache_ttl = 5000

# config port websocket over mqtt
mqtt.listeners.tcp.default = 1883
web_mqtt.tcp.port = 15675

# Desabilita o usuário guest remotamente
loopback_users.guest = false